---
ansible_user: labadmin
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_ssh_public_key: ~/.ssh/id_ed25519.pub

ansible_sudo_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63386338343661626535643865613764333631346363663766393365393833643536336536633164
          6339313834636162623761666534396437393233353030370a396531363032633230316638376439
          35316361343433323638313039383965373866663734393535306236626262373332396630303333
          3666336661393836300a326139386333353534333061623464373364396165663433353861336535
          6638

abuseipdb_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61356238626635366162663936316537316237646131653235613565306432643039313261386439
          3737303138373261316238323565323332663364333462370a613435346339333164373439613933
          64636364633734386434356230323632623566396137633333613331653464343762313936636430
          3338383130653739390a373264313365373432313930303462343762336365343539363632306261
          39623764633661623938343230323134306437666365356463363238613735393661663530663735
          37616162313638376466656336336164656366613132303163336538663037383435393939396566
          35366235643137323930356562343935646234646466353465626631393037303361393464366263
          39323265303838343065633138613364313037643631643635316161643365386631313164306233
          6332

ntfy_topic: air-github # Topic for ntfy notifications
