$ANSIBLE_VAULT;1.1;AES256
61393533393733326666616163336461323332333930653862663930366536396363646665633561
3437343264343466616436333433366436376565653330380a643837396638636565356166386537
63316631653534373865663466323736346338633439613765323662656631643762316562643737
6632393433353431310a653335366566666362633861616439356565373530366566633364643539
31373263343431666439666138373530656333366463613933616231623238303333383230663161
35666636616433333431613731613031633261373433393631646434366330363735393730623136
64346432623333663234626136636661353030646165653331363464643739633663623832316361
63356532373037653161373531653436393165656665383333613937323964373931303362383434
39323434633235643164666134313735663531303962656633636433326365313731306132353436
66323330643666363031663536333538663964333764353634386534346633663634666134376339
33633365623361643164623832323363373763623439316430333832326563303831316135663330
62633937376432626336333438393836306333313032373332316138656665663761626364643166
33636531633834303362653430633039393063646139326238316438353636373737373036643536
34303336323839613037323036363461383331363939366337326361343361363965623565613162
31303833316538313634383332326431636134663231666232353166626432326233323333376363
39663535633534613463303464363763616536383435313238666263646466333338636463363166
62633130623739373132306666393365363361366532383332396532333034353564646437653862
35613866323034643435313137323761316433613835653438663133636231653838356233343132
666234366632373637613934633466616364
