---
ansible_user: labadmin
ansible_ssh_private_key_file: ~/.ssh/id_ed25519 
ansible_ssh_public_key: ~/.ssh/id_ed25519.pub

ansible_sudo_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63386338343661626535643865613764333631346363663766393365393833643536336536633164
          6339313834636162623761666534396437393233353030370a396531363032633230316638376439
          35316361343433323638313039383965373866663734393535306236626262373332396630303333
          3666336661393836300a326139386333353534333061623464373364396165663433353861336535
          6638