---
- name: Check if K3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install K3s
  ansible.builtin.shell: |
    set -o pipefail
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /var/lib/rancher/k3s/server/node-token
    executable: /bin/bash
  when: not k3s_binary.stat.exists

- name: Ensure K3s service is running and enabled
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: true

- name: Wait for kubeconfig file generation
  ansible.builtin.wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    state: present
    timeout: 30

# Prepare local directory to store the cluster credentials
- name: Create local .kube directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0750'
  delegate_to: localhost
  become: false

# Fetch to a temp file
- name: Fetch kubeconfig to temporary location
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/k3s_config_temp
    flat: true
  become: true
  changed_when: false

# Edit the temp file
- name: Replace localhost IP with Server IP in temp config
  ansible.builtin.replace:
    path: /tmp/k3s_config_temp
    regexp: '127\.0\.0\.1'
    replace: "{{ lab_ip }}"
  delegate_to: localhost
  become: false
  changed_when: false

# Copy to final destination
- name: Update local kubeconfig only if changed
  ansible.builtin.copy:
    src: /tmp/k3s_config_temp
    dest: ~/.kube/config
    mode: '0600'
  delegate_to: localhost
  become: false
