---
- name: Connection check
  hosts: lab_servers
  gather_facts: false

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Print msg
      ansible.builtin.debug:
        msg: Hello world
