---
collections:
  - name: community.general
    version: 8.2.0

  - name: ansible.posix
    version: 1.5.0

  - name: community.docker
    version: 3.6.0

  - name: kubernetes.core
    version: 3.0.0
