---
- name: Configure SSH
  ansible.builtin.import_tasks:
    file: ssh.yml

- name: Configure Firewall
  ansible.builtin.import_tasks:
    file: firewall.yml

- name: Configure Fail2Ban
  ansible.builtin.import_tasks:
    file: fail2ban.yml
