name: Ansible Quality Gate

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ansible/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ansible/**'

jobs:
  lint:
    name: Ansible Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python Tools
        run: pip install yamllint ansible

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install -r ansible/requirements.yml

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install -r ansible/requirements.yml

      - name: Run Yamllint
        run: yamllint -c .yamllint -f standard ansible/

      - name: Run Ansible Syntax Check
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: |
          ansible-playbook ansible/playbooks/*.yml --syntax-check

      - name: Run Ansible Lint
        uses: ansible/ansible-lint@v6
        with:
          args: "ansible/"
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
